
stages:
  - build

build_image:
  stage: build
  script:
    - docker build -f deployment/Dockerfile.prod -t docker-registry.ebrains.eu/neuromorphic/nmpi_job_manager .
    - echo $DOCKER_REGISTRY_USER
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_SECRET docker-registry.ebrains.eu
    - docker push docker-registry.ebrains.eu/neuromorphic/nmpi_job_manager
  tags:
    - shell-runner

