version: "3.7"

services:
  nmpi-job-manager-app:
    image: docker-registry.ebrains.eu/neuromorphic/nmpi_job_manager
    container_name: nmpi-job-manager-app
    build:
      context: ..
      dockerfile: deployment/Dockerfile.prod
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
    ports:
      - "443:443"
